# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Tue Jul  8 21:40:44 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(317, 571)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.points_table_widget = QtGui.QTableWidget(Form)
        self.points_table_widget.setObjectName(_fromUtf8("points_table_widget"))
        self.points_table_widget.setColumnCount(2)
        self.points_table_widget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.points_table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.points_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.points_table_widget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.points_table_widget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.add_push_button = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.add_push_button.setFont(font)
        self.add_push_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1403292182_Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_push_button.setIcon(icon)
        self.add_push_button.setObjectName(_fromUtf8("add_push_button"))
        self.verticalLayout.addWidget(self.add_push_button)
        self.del_push_button = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.del_push_button.setFont(font)
        self.del_push_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1403362103_Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_push_button.setIcon(icon1)
        self.del_push_button.setObjectName(_fromUtf8("del_push_button"))
        self.verticalLayout.addWidget(self.del_push_button)
        spacerItem = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.save_push_button = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.save_push_button.setFont(font)
        self.save_push_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1404769242_Download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_push_button.setIcon(icon2)
        self.save_push_button.setObjectName(_fromUtf8("save_push_button"))
        self.verticalLayout.addWidget(self.save_push_button)
        self.load_push_button = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.load_push_button.setFont(font)
        self.load_push_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1404769249_Upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_push_button.setIcon(icon3)
        self.load_push_button.setObjectName(_fromUtf8("load_push_button"))
        self.verticalLayout.addWidget(self.load_push_button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.d2_radio_button = QtGui.QRadioButton(self.groupBox)
        self.d2_radio_button.setChecked(True)
        self.d2_radio_button.setObjectName(_fromUtf8("d2_radio_button"))
        self.verticalLayout_2.addWidget(self.d2_radio_button)
        self.d3_radio_button = QtGui.QRadioButton(self.groupBox)
        self.d3_radio_button.setChecked(False)
        self.d3_radio_button.setObjectName(_fromUtf8("d3_radio_button"))
        self.verticalLayout_2.addWidget(self.d3_radio_button)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.methods_combo_box = QtGui.QComboBox(Form)
        self.methods_combo_box.setObjectName(_fromUtf8("methods_combo_box"))
        self.methods_combo_box.addItem(_fromUtf8(""))
        self.methods_combo_box.addItem(_fromUtf8(""))
        self.methods_combo_box.addItem(_fromUtf8(""))
        self.methods_combo_box.addItem(_fromUtf8(""))
        self.methods_combo_box.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.methods_combo_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.border_spin_box = QtGui.QDoubleSpinBox(Form)
        self.border_spin_box.setObjectName(_fromUtf8("border_spin_box"))
        self.horizontalLayout_4.addWidget(self.border_spin_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.radius_spin_box = QtGui.QDoubleSpinBox(Form)
        self.radius_spin_box.setObjectName(_fromUtf8("radius_spin_box"))
        self.horizontalLayout_5.addWidget(self.radius_spin_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.clasters_number_spin_box = QtGui.QSpinBox(Form)
        self.clasters_number_spin_box.setObjectName(_fromUtf8("clasters_number_spin_box"))
        self.horizontalLayout_6.addWidget(self.clasters_number_spin_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.centres_line_edit = QtGui.QLineEdit(Form)
        self.centres_line_edit.setObjectName(_fromUtf8("centres_line_edit"))
        self.horizontalLayout_7.addWidget(self.centres_line_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.exit_push_button = QtGui.QPushButton(Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1403362143_Cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_push_button.setIcon(icon4)
        self.exit_push_button.setObjectName(_fromUtf8("exit_push_button"))
        self.horizontalLayout.addWidget(self.exit_push_button)
        self.count_push_button = QtGui.QPushButton(Form)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1404855380_Next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.count_push_button.setIcon(icon5)
        self.count_push_button.setObjectName(_fromUtf8("count_push_button"))
        self.horizontalLayout.addWidget(self.count_push_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.exit_push_button, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.points_table_widget, self.add_push_button)
        Form.setTabOrder(self.add_push_button, self.del_push_button)
        Form.setTabOrder(self.del_push_button, self.save_push_button)
        Form.setTabOrder(self.save_push_button, self.load_push_button)
        Form.setTabOrder(self.load_push_button, self.d2_radio_button)
        Form.setTabOrder(self.d2_radio_button, self.d3_radio_button)
        Form.setTabOrder(self.d3_radio_button, self.methods_combo_box)
        Form.setTabOrder(self.methods_combo_box, self.border_spin_box)
        Form.setTabOrder(self.border_spin_box, self.radius_spin_box)
        Form.setTabOrder(self.radius_spin_box, self.clasters_number_spin_box)
        Form.setTabOrder(self.clasters_number_spin_box, self.centres_line_edit)
        Form.setTabOrder(self.centres_line_edit, self.exit_push_button)
        Form.setTabOrder(self.exit_push_button, self.count_push_button)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Кластерный анализ", None, QtGui.QApplication.UnicodeUTF8))
        self.points_table_widget.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Точки</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        item = self.points_table_widget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.points_table_widget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        item = self.points_table_widget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.add_push_button.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Добавить точку</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.del_push_button.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Удалить точку</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.save_push_button.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Сохранить точки в файл</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.save_push_button.setWhatsThis(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.load_push_button.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Загрузить точки из файла</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.load_push_button.setWhatsThis(QtGui.QApplication.translate("Form", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Размерность: ", None, QtGui.QApplication.UnicodeUTF8))
        self.d2_radio_button.setText(QtGui.QApplication.translate("Form", "Двумерная", None, QtGui.QApplication.UnicodeUTF8))
        self.d3_radio_button.setText(QtGui.QApplication.translate("Form", "Трехмерная", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Метод:", None, QtGui.QApplication.UnicodeUTF8))
        self.methods_combo_box.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Выберите метод кластеризации</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.methods_combo_box.setItemText(0, QtGui.QApplication.translate("Form", "Последовательная кластеризация", None, QtGui.QApplication.UnicodeUTF8))
        self.methods_combo_box.setItemText(1, QtGui.QApplication.translate("Form", "Кинга", None, QtGui.QApplication.UnicodeUTF8))
        self.methods_combo_box.setItemText(2, QtGui.QApplication.translate("Form", "К-средних", None, QtGui.QApplication.UnicodeUTF8))
        self.methods_combo_box.setItemText(3, QtGui.QApplication.translate("Form", "\"Форель\"", None, QtGui.QApplication.UnicodeUTF8))
        self.methods_combo_box.setItemText(4, QtGui.QApplication.translate("Form", "\"Краб\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Пороговое расстояние: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Радиус:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Число кластеров:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Центры кластеров:", None, QtGui.QApplication.UnicodeUTF8))
        self.centres_line_edit.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Введите центры через точку с запятой,например:</p><p><span style=\" font-size:12pt; font-weight:600;\">2;5;7</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_push_button.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Выйти из программы</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_push_button.setText(QtGui.QApplication.translate("Form", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.count_push_button.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Выполнить кластеризацию и отобразить результаты</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.count_push_button.setText(QtGui.QApplication.translate("Form", "Рассчитать", None, QtGui.QApplication.UnicodeUTF8))

